Fix TypeError in getStateToCacheAndObserveFor
it turns out that getStateToCacheAndObserveFor notifies
with a kwargs 'observer'. this trickles down to `notifyObserver`
which which has an 'observer' parameter, resulting in:

    exceptions.TypeError: notifyObserver() got multiple values for keyword
                          argument 'observer'

The fix is to just change the parameter to 'obs', to avoid the
collision.